# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Notes to self
description: >- # this means to ignore newlines until "baseurl:"
  Alex C-G's blog
baseurl: "/jekyll-4-test" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: alexcg
github_username: alexcg1

# Build settings
#theme: minima
theme: jekyll-theme-so-simple
remote_theme: "mmistakes/so-simple-theme@3.2.0"
#remote_theme: mmistakes/minimal-mistakes
#remote_theme: benbalter/retlab

plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-include-cache
  - jekyll-paginate

#minima:
  #social_links:
    #- { platform: github,  user_url: "https://github.com/alexcg1" }
    #- { platform: twitter, user_url: "https://twitter.com/alexcg" }

show_excerpts: true

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
#
# So Simple theme stuff
read_time: true
words_per_minute: 200
paginate: 10  # amount of posts to show per page
paginate_path: /page/:num/
category_archive_path: "/categories/#"
tag_archive_path: "/tags/#"
search_full_content: true
author:
  name: Alex C-G
  twitter: alexcg
  picture: /images/me.jpg
footer_links:
  - title: Twitter
    url: https://twitter.com/alexcg
    icon: fab fa-twitter-square
  - title: GitHub
    url: https://github.com/alexcg1
    icon: fab fa-github-square
  - title: Feed
    url: atom.xml
    icon: fas fa-rss-square
copyright: "2018-2024 Alex C-G"
site:
  logo: "/images/me.jpg"
